version: '3'

services:
  mysql-container:
    build: Database/

    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=smart_home_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-storage:/var/lib/mysql

  house-cmu:
    build: HouseSimulator/
    ports:
      - "5051:5050"

  house-mse:
    build: HouseSimulator/
    ports:
      - "5050:5050"

  platform:
    build:
      context: Platform/
    depends_on:
      - mysql-container
      - house-cmu
      - house-mse
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql-container
      - DB_PORT=3306
      - DB_NAME=smart_home_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword

volumes:
  mysql-storage:
