name: Java CI 

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Step 3: Build the project with Gradle
    - name: build_and_test with Gradle
      run: ./gradlew build
      working-directory: ./smart-home/Platform

    # Step 4: Upload Jacoco HTML Report
    - name: Upload Jacoco Report
      if: always() # Ensure this step runs even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: smart-home/Platform/build/jacocoHtml/


  system-test:
    runs-on: self-hosted
    needs: build_and_test
    steps:
      - uses: actions/checkout@v4

      - name: Run docker Compose
        working-directory: ./smart-home/Platform
        run: |
          docker-compose up -d --build
          sleep 30
          docker-compose up -d --build
              
      - name : set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install Python Dependencies
        run: pip install pytest requests

      - name: Run system tests
        working-directory: ./smart-home/Platform/src/test/python
        run: python3 -m pytest

      - name: Bring server down
        working-directory: ./smart-home/Platform
        run: docker-compose down

  deploy:
    needs : build_and_test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - name: Copy Repository onto Cloud
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: "./"
          target: "~/prod"
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}

      - name: Restart All Instances on Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }} 
          port: ${{ secrets.PORT }}
          script: |
            cd ~/prod/smart-home
            chmod +x build-and-run.sh
            ./build-and-run.sh


  
