name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Step 3: Verify Platform directory contents
    - name: Verify Platform directory contents
      run: ls -R smart-home/Platform

    # Step 4: Set up Gradle Wrapper
    - name: Set up Gradle Wrapper
      run: ./gradlew wrapper
      working-directory: ./smart-home/Platform

    # Step 5: Build the project with Gradle
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./smart-home/Platform

    # Step 6: Run tests
    - name: Run Tests
      run: ./gradlew test
      working-directory: ./smart-home/Platform
